server:
  port: 8888
spring:
  profiles:
    active:
    - native
  cloud:
    config:
      server:
        native:
          search-locations:
          - file:///c:\Curso Java EE\temp javaee\config