server:
  port: 8000
spring:
  application:
    name: servicio-coches
eureka:
  instance:
    instance-id: a13e34
    hostname: a13e34
  client:
    serviceUrl:
      defaultZone: http://10.1.3.100:8761/eureka